home/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from . import views, ajax

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.blogs, name='blogs'),
    path('blogs/<int:id>', views.blogdetail, name='blogdetail'),
    path('about/', views.about, name='about'),
    path('blogs/<int:id>/ajax/', ajax.translation, name='translation'),
    path('blogs/<int:id>/ajax/word', ajax.trans_word, name='trans_word'),
    path('blogs/<int:id>/ajax/sentence', ajax.trans_sentence, name='trans_sentence'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': 
		settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': 
        settings.STATIC_ROOT}),
]

learn_supporter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from urllib.parse import quote
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(models.Model):
	id = models.AutoField(primary_key=True)
	codename = models.CharField(max_length=250, blank=True, null=True, unique=True)
	name = models.CharField(max_length=250, blank=True, null=True)
	note = models.CharField(max_length=250, blank=True, null=True)
	createdate = models.DateField(auto_now_add=True, blank=True, null=True)
	editdate = models.DateTimeField(auto_now=True, blank=True, null=True)
	is_enable = models.BooleanField(default=True, blank=True, null=True)

	def __str__(self):
		return self.codename

	class Meta:
		managed = True
		db_table = 'Category'

class Blog(models.Model):
	STATUS_CHOICES = (
		('d', 'Draft'),
		('p', 'Published'),
	) 
	author = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
	id = models.AutoField(primary_key=True)
	category = models.ForeignKey('Category', models.DO_NOTHING, null=True)
	title = models.CharField(max_length=100)
	photo = models.CharField(max_length=250, blank=True, null=True)
	# file = models.FileField(upload_to='musics/')
	audio = models.CharField(max_length=250, blank=True, null=True)
	content = models.TextField(blank=True, null=True)
	translation = models.TextField(blank=True, null=True)
	text = models.TextField(blank=True, null=True)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES)
	# slug = models.SlugField(max_length=250, null=True, blank=True)
	createdate = models.DateField(auto_now_add=True, blank=True, null=True)
	editdate = models.DateTimeField(auto_now=True, blank=True, null=True) 
	is_enable = models.BooleanField(default=True, blank=True, null=True)
	note = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Blog, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-createdate']
		managed = True
		db_table = 'Blog'

class Word(models.Model):
	word = models.CharField(max_length=100, blank=True, null=True)
	blog = models.ForeignKey('Blog', models.CASCADE, null=True)
	type = models.CharField(max_length=100, blank=True, null=True)
	pinyin = models.CharField(max_length=100, blank=True, null=True)
	meaning = models.CharField(max_length=100, blank=True, null=True)
	sentence = models.TextField(blank=True, null=True)

	class Meta:
		managed = True
		db_table = 'Word'


class Table(models.Model):
	id = models.AutoField(primary_key=True)
	blog = models.ForeignKey('Blog', models.CASCADE, null=True)
	content = RichTextUploadingField(blank=True, null=True)

	class Meta:
		managed = True
		db_table = 'Table'

home/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
import json
from django.http import JsonResponse



def index(request):
     blogs = Blog.objects.all().order_by('-createdate').exclude(is_enable=False)

     context = {
          'blogs': blogs,
     }
     return render(request, 'homepage/index.html', context)

def blogs(request):
     blogs = Blog.objects.all().order_by('-createdate').exclude(is_enable=False)

     context = {
          'blogs': blogs,
     }
     return render(request, 'homepage/blog.html', context)

def blogdetail(request, id):
     blog = get_object_or_404(Blog, id=id, is_enable=True)

     context = {
          'blog': blog,
     }
     return render(request, 'homepage/blog-detail.html', context)

def about(request):
     return render(request, 'homepage/about.html')

home/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>{% block title %}{% endblock %}</title>
    
    <!--== Favicon ==-->
    <link rel="shortcut icon" href="{% static 'homepage/img/favicon.ico' %}" type="image/x-icon" />

    <!--== Google Fonts ==-->
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One:400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <!--== Bootstrap CSS ==-->
    <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <!--== Font-awesome Icons CSS ==-->
    <link href="{% static 'homepage/css/font-awesome.min.css' %}" rel="stylesheet"/>
    <!--== Pe Icon 7 Min Icons CSS ==-->
    <link href="{% static 'homepage/css/pe-icon-7-stroke.min.css' %}" rel="stylesheet"/>
    <!--== Ionicons CSS ==-->
    <link href="{% static 'homepage/css/ionicons.css' %}" rel="stylesheet"/>
    <!--== Animate CSS ==-->
    <link href="{% static 'homepage/css/animate.css' %}" rel="stylesheet"/>
    <!--== Aos CSS ==-->
    <link href="{% static 'homepage/css/aos.css' %}" rel="stylesheet"/>
    <!--== FancyBox CSS ==-->
    <link href="{% static 'homepage/css/jquery.fancybox.min.css' %}" rel="stylesheet"/>
    <!--== Slicknav CSS ==-->
    <link href="{% static 'homepage/css/slicknav.css' %}" rel="stylesheet"/>
    <!--== Swiper CSS ==-->
    <link href="{% static 'homepage/css/swiper.min.css' %}" rel="stylesheet"/>
    <!--== Slick CSS ==-->
    <link href="{% static 'homepage/css/slick.css' %}" rel="stylesheet"/>
    <!--== Main Style CSS ==-->
    <link href="{% static 'homepage/css/style.css' %}" rel="stylesheet" />
    <!-- custom css -->
    <link href="{% static 'homepage/css/my-css.css' %}" rel="stylesheet" />
</head>

<div class="wrapper home-default-wrapper">
  
    <!--== Start Header Wrapper ==-->
    <header class="header-wrapper">
      <div class="header-middle">
        <div class="container">
          <div class="row row-gutter-0 align-items-center">
            <div class="col-12">
              <div class="header-align">
                <div class="header-align-left">
                  <div class="header-logo-area">
                    <a href="index.html">
                      <img class="logo-main" src="{% static 'homepage/img/logo.png' %}" alt="Logo" />
                      <img class="logo-light" src="{% static 'homepage/img/logo.png' %}" alt="Logo" />
                    </a>
                  </div>
                </div>
                <div class="header-align-center">
                  <div class="header-search-box">
                    <form action="#" method="post">
                      <div class="form-input-item">
                        <label for="search" class="sr-only">Search Everything</label>
                        <input type="text" id="search" placeholder="Search Everything">
                        <button type="submit" class="btn-src">
                          <i class="pe-7s-search"></i>
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="header-area header-default sticky-header">
        <div class="container">
          <div class="row row-gutter-0 align-items-center">
            <div class="col-4 col-sm-6 col-lg-2">
              <div class="header-logo-area">
                <a href="{% url 'home:index' %}">
                  <img class="logo-main" src="{% static 'homepage/img/logo.png' %}" alt="Logo" />
                  <img class="logo-light" src="{% static 'homepage/img/logo.png' %}" alt="Logo" />
                </a>
              </div>
            </div>
            <div class="col-lg-8 sticky-md-none">
              <div class="header-navigation-area d-none d-md-block">
                <ul class="main-menu nav position-relative">
                  <li><a class="ml--2" href="{% url 'home:index' %}">Home</a></li>
                  <li><a href="{% url 'home:about' %}">About</a></li>
                  <li><a href="{% url 'home:blogs' %}">Blog</a></li>
                  <li><a href="contact.html">Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="col-8 col-sm-6 col-lg-2">
              <div class="header-action-area">
                <div class="header-action-search">
                  <button class="btn-search btn-search-menu">
                    <i class="pe-7s-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!--== End Header Wrapper ==-->
    {% block content %}

    {% endblock %}
</div>

<!--=======================Javascript============================-->

<!--=== Modernizr Min Js ===-->
<script src="{% static 'homepage/js/modernizr.js' %}"></script>
<!--=== jQuery Min Js ===-->
<script src="{% static 'homepage/js/jquery-main.js' %}"></script>
<!--=== jQuery Migration Min Js ===-->
<script src="{% static 'homepage/js/jquery-migrate.js' %}"></script>
<!--=== Popper Min Js ===-->
<script src="{% static 'homepage/js/popper.min.js' %}"></script>
<!--=== Bootstrap Min Js ===-->
<script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
<!--=== jquery Appear Js ===-->
<script src="{% static 'homepage/js/jquery.appear.js' %}"></script>
<!--=== jquery Swiper Min Js ===-->
<script src="{% static 'homepage/js/swiper.min.js' %}"></script>
<!--=== jquery Fancybox Min Js ===-->
<script src="{% static 'homepage/js/fancybox.min.js' %}"></script>
<!--=== jquery Aos Min Js ===-->
<script src="{% static 'homepage/js/aos.min.js' %}"></script>
<!--=== jquery Slicknav Js ===-->
<script src="{% static 'homepage/js/jquery.slicknav.js' %}"></script>
<!--=== jquery Countdown Js ===-->
<script src="{% static 'homepage/js/jquery.countdown.min.js' %}"></script>
<!--=== jquery Tippy Js ===-->
<script src="{% static 'homepage/js/tippy.all.min.js' %}"></script>
<!--=== Isotope Min Js ===-->
<script src="{% static 'homepage/js/isotope.pkgd.min.js' %}"></script>
<!--=== Parallax Min Js ===-->
<script src="{% static 'homepage/js/parallax.min.js' %}"></script>
<!--=== Slick  Min Js ===-->
<script src="{% static 'homepage/js/slick.min.js' %}"></script>
<!--=== jquery Wow Min Js ===-->
<script src="{% static 'homepage/js/wow.min.js' %}"></script>
<!--=== jquery Zoom Min Js ===-->
<script src="{% static 'homepage/js/jquery-zoom.min.js' %}"></script>

<!--=== Custom Js ===-->
<script src="{% static 'homepage/js/custom.js' %}"></script>
<script src="{% static 'homepage/js/my-function.js' %}"></script>
</html>

home/templates/homepage/blog-detail.html
{% extends 'homepage/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from template.hasthemes.com/kidol/kidol/blog-details-no-sidebar.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 Nov 2021 15:06:33 GMT -->

<head>
  <title>{% block title %}Blog-detail{% endblock %}</title>
  <meta charset="utf-8">
</head>
{% block content %}

<body onload="load()">
  <!--wrapper start-->
  <div class="wrapper page-blog-details-wrapper">

    <!--== Start Preloader Content ==-->
    <div class="preloader-wrap">
      <div class="preloader">
        <span class="dot"></span>
        <div class="dots">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
    <!--== End Preloader Content ==-->

    <main class="main-content">
      <!--== Start Page Title Area ==-->
      <section class="page-title-area">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-12 m-auto">
              <div class="page-title-content text-center">
                <h2 class="title">Blog</h2>
                <div class="bread-crumbs"><a href="{% url 'home:index' %}"> Home </a><span class="breadcrumb-sep"> //
                  </span><span class="active"> Blog</span></div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!--== End Page Title Area ==-->

      <!--== Start Blog Area Wrapper ==-->
      <section class="blog-details-area">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="post-details-content">
                <div class="post-details-body">
                  <div class="thumb">
                    <img class="w-100" src="{{ blog.photo }}" alt="Image" />
                  </div>
                  <div class="content">
                    <div class="meta">By, <a class="author" href="blog.html">{{ blog.author }}</a><span
                        class="dots"></span><span class="post-date">{{ blog.editdate|date:"d N, o" }}</span></div>
                    <h4 class="title">{{ blog.title }}</h4>
                    <!-- Load audio -->
                    <div class="content">
                      <audio controls>
                        <source src="{{ blog.audio }}" type="audio/mpeg">
                      </audio>
                    </div>

                    <div>
                      <button onclick="show('btv')" class="w3-button w3-white w3-border w3-border-red w3-round-large">
                        Bảng Từ Vựng
                      </button>
                      <button onclick="show('exercise')" class="w3-button w3-white w3-border w3-border-red w3-round-large">
                        Bài Tập
                      </button>
                      <button onclick="show('content')" class="w3-button w3-white w3-border w3-border-red w3-round-large">
                        Script
                      </button>
                    </div>
                    <!-- Hiển thị nội dung -->
                    <div style="text-align: justify; text-justify: inter-word;" id="content"></div>
                    <!-- Kết thúc hiển thị -->

                    <div id="exercise">

                      ha ha ha
                    </div>

                    <div id="btv">
                      hello
                    </div>
                  </div>
                </div>
              </div>
              <div class="comment-area">
                <div class="row">
                  <div class="col-lg-12">
                    <div class="comment-view-area">
                      <h2 class="title">3 Comments</h2>
                      <div class="comment-content">
                        <div class="single-comment">
                          <div class="author-info">
                            <div class="thumb">
                              <img src="{% static 'homepage/img/blog/details/1.png' %}" alt="Image">
                            </div>
                            <div class="author-details border-bottom">
                              <ul>
                                <li>Aidyn Cody <span> - 25 May, 2121</span></li>
                              </ul>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididun ut labore et dolore magna aliqua.</p>
                              <a class="btn-theme" href="#/">Reply</a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="comment-content comment-content-style2">
                        <div class="single-comment">
                          <div class="author-info">
                            <div class="thumb">
                              <img src="{% static 'homepage/img/blog/details/2.png' %}" alt="Image">
                            </div>
                            <div class="author-details">
                              <ul>
                                <li>Jivan Cody <span> - 25 May, 2121</span></li>
                              </ul>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididun ut labore et dolore magna aliqua.</p>
                              <a class="btn-theme" href="#/">Reply</a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="comment-content">
                        <div class="single-comment">
                          <div class="author-info">
                            <div class="thumb pt-38">
                              <img src="{% static 'homepage/img/blog/details/3.png' %}" alt="Image">
                            </div>
                            <div class="author-details border-top pt-37">
                              <ul>
                                <li>Rose Cody <span> - 25 May, 2121</span></li>
                              </ul>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididun ut labore et dolore magna aliqua.</p>
                              <a class="btn-theme" href="#/">Reply</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="comment-form-wrap mb-lg-0">
                      <form class="comment-form-wrapper" id="comment-form"
                        action="https://whizthemes.com/mail-php/raju/arden/mail.php" method="post">
                        <div class="row">
                          <div class="col-lg-12">
                            <div class="section-title m-0">
                              <h2 class="title">Leave a Comment</h2>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-lg-12">
                            <div class="row">
                              <div class="col-md-6">
                                <div class="form-group">
                                  <input class="form-control" type="text" placeholder="Name *">
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="form-group">
                                  <input class="form-control" type="email" placeholder="Email *">
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="form-group">
                                  <input class="form-control" type="text" placeholder="Subject (Optinal)">
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="form-group">
                                  <textarea class="form-control" placeholder="Message"></textarea>
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="form-group">
                                  <button class="btn btn-theme" type="submit">Send a Comment</button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!--== End Blog Area Wrapper ==-->
      <!-- Start translate content -->
      <div id="tran-area"></div>
      <!-- End translate content -->

    </main>

  </div>

</body>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script>
  var glb_data = ''
  function load() {
    $.ajax({
      url: "{% url 'home:translation' blog.id %}",
      type: 'GET',
      data: {

      },
      success: function (data) {
        console.log(data.list)
        render_data(data.list)

      }
    })
  }

  function render_data(data) {
    var div = document.createElement('div')
    count = 0;
    data.forEach(item => {
      var d = document.createElement('p')
      item.forEach(element => {

        if (element != '') {
          tmp = document.createElement('span')
          tmp.classList.add('hover-me')
          tmp.setAttribute('id', `para-${count + 1}`)
          element.forEach(child => {

            if (child != '') {
              tmp2 = document.createElement('span')
              tmp2.classList.add('hover-me2')
              tmp2.innerHTML = (child)
              tmp.appendChild(tmp2)
            }
          })

          d.appendChild(tmp)
          count++;
        }
      })
      div.append(d);


    });


    document.getElementById("content").appendChild(div)
    bindHover()
    
  };
  var glb_pos=[]
  function bindHover() {
    
    $('.hover-me').hover(
      function () {
        trans_sentence((this.id).split('-')[1]);

        event.stopPropagation();
        $('#tran-area').css('display', 'inline-block');
        // var e = window.event;
        // var posX = e.clientX;
        // var posY = e.clientY;
        // $('#tran-area').offset({ top: posY + window.scrollY + 10, left: window.innerWidth*0.2 })
        let pos = $(this).offset();

        height = $(this).height()
       
        let top = pos.top + height;
        let left = $('#content').offset().left

        $('#tran-area').offset({ top: top*1.001, left: left })
        glb_data = $('#tran-area').offset()
        // $('#tran-area').width($(this).width())
      },
      () => {
        event.stopPropagation();
        $('#tran-area').hide()
      }
    )
    $('.hover-me2').click(
      function () {
        let pos = $(this).offset();
        trans_word(this,pos);
        
      }
    );
    $('.hover-me2').hover(
      function () {

      },
      function () {
        let pos = glb_pos
        let top = pos.top;
        let left = pos.left

        $('#tran-area').offset({ top: top, left: left })

        this.style.backgroundColor = ''
        if (glb_data != '') {
          render_translate(glb_data, 'sentence')
        }

      }
    )
  }

  function trans_sentence(pid) {
    // console.log(pid)
    $.ajax({
      url: "{% url 'home:trans_sentence' blog.id %}",
      type: 'GET',
      data: {
        "id": pid - 1,
      },
      success: function (data) {
        glb_data = data
        render_translate(data, 'sentence')
        
      }
    })
  }
  function trans_word(e,pos) {
    // console.log(word)
    let word = e.innerText
    $.ajax({
      url: "{% url 'home:trans_word' blog.id %}",
      type: 'GET',
      data: {
        word: word
      },
      success: function (data) {
        // console.log(data)
        e.style.backgroundColor = 'rgba(0, 174, 255, 0.562)'
        render_translate(data, 'word');
        let top = pos.top + 20;
        let left = pos.left
        glb_pos = $('#tran-area').offset()
        $('#tran-area').offset({ top: top, left: left })
      }
    })
  }

</script>
{% endblock %}

</html>